name: Keep Render Service Awake

on:
  schedule:
    - cron: '*/12 * * * *' # Every 12 minutes
  workflow_dispatch:       # Allow manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Web Service
        run: curl -s -o /dev/null -w "%{http_code}" https://binance-traderbot.onrender.com/
