name: Keep Webhook Service Alive

on:
  schedule:
    - cron: '*/6 * * * *'  # Every 6 minutes
  workflow_dispatch:        # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Webhook Service
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "Pinging $WEBHOOK_URL"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$WEBHOOK_URL")
          echo "HTTP status: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "Ping failed with HTTP $STATUS"
            exit 1
          fi
